"""Crear tablas base del Sprint 1

Revision ID: 39dd888f4030
Revises: 22222d1ae8f4
Create Date: 2026-09-30 19:46:07.198580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39dd888f4030'
down_revision: Union[str, Sequence[str], None] = '22222d1ae8f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cuenta_titular_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=True),
    sa.Column('grupo_sanguineo', sa.String(length=15), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('subtipo', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_titular_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alergia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('perfil_id', sa.UUID(), nullable=False),
    sa.Column('sustancia', sa.String(length=120), nullable=False),
    sa.Column('severidad', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacto_emergencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('perfil_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('relacion', sa.String(length=50), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('usuarios', 'rol')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('rol', postgresql.ENUM('titular', 'cuidador', name='rolusuario'), autoincrement=False, nullable=False))
    op.drop_table('contacto_emergencia')
    op.drop_table('alergia')
    op.drop_table('perfil')
    # ### end Alembic commands ###
